In [1]:
import pandas as pd
import patsy as py
import numpy as np

In [2]:
D=pd.read_excel("https://data.hossam.kr/C02/dum.xlsx")
data=pd.DataFrame(D)

0 을 붙어야 상수항을 만들지 못함

In [3]:
py.dmatrix("성별 +0",data)

DesignMatrix with shape (20, 2)
  성별[남자]  성별[여자]
       1       0
       0       1
       0       1
       1       0
       1       0
       1       0
       1       0
       0       1
       0       1
       1       0
       0       1
       0       1
       0       1
       1       0
       0       1
       0       1
       1       0
       0       1
       0       1
       0       1
  Terms:
    '성별' (columns 0:2)

In [4]:
dm=py.dmatrix("성별:비만도 + 0",data)

In [25]:
pd.DataFrame(columns=dm.design_info.column_names,data=dm.view())

,성별[남자]:비만도[경도],성별[여자]:비만도[경도],성별[남자]:비만도[고도],성별[여자]:비만도[고도],성별[남자]:비만도[정상],성별[여자]:비만도[정상]
0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,1.0,0.0,0.0,0.0,0.0
9,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,1.0
11,0.0,0.0,0.0,0.0,0.0,1.0
12,0.0,0.0,0.0,0.0,0.0,1.0
13,0.0,0.0,0.0,0.0,1.0,0.0
14,0.0,0.0,0.0,1.0,0.0,0.0
15,0.0,1.0,0.0,0.0,0.0,0.0
16,0.0,0.0,1.0,0.0,0.0,0.0
17,0.0,1.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,1.0
19,0.0,1.0,0.0,0.0,0.0,0.0

In [24]:
dm.view()

array([[0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.]])