In [2]:
import pandas as pd
import numpy as np
import sys
import os

In [3]:
D=pd.read_csv(r"C:\Users\SAMSUNG\Desktop\공부파일들\excel\한국복지패널\공부용.csv")
D.drop(D.columns[:2],axis=1,inplace=True)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_19708\24473341.py:1: DtypeWarning: Columns (831,834,836) have mixed types. Specify dtype option on import or set low_memory=False.
  D=pd.read_csv(r"C:\Users\SAMSUNG\Desktop\공부파일들\excel\한국복지패널\공부용.csv")

,가구형태/주거급여 수급형태_x,6. 주거/이사경험 여부_x,6. 주거/이사 사유_x,6. 주거/주택유형_x,6. 주거/주거위치_x,6. 주거/방수_x,6. 주거/주거면적_x,6. 주거/집의 (등기상) 점유형태_x,6. 주거/임대주택 유형_x,6. 주거/집의 가격_x,...,12. 국민기초생활보장/(주거급여)두번째_급여를 받은 기간_y.1,12. 국민기초생활보장/(주거급여)세번째_급여를 받은 년_y,12. 국민기초생활보장/(주거급여)세번째_급여를 받은 기간_y,12. 국민기초생활보장/(주거급여)세번째_급여를 받은 년_y.1,12. 국민기초생활보장/(주거급여)세번째_급여를 받은 기간_y.1,12. 국민기초생활보장/(주거급여)12월 말까지 급여를 받게 된 이유_y,12. 국민기초생활보장/(주거급여)국민기초생활보장 급여수준 평가_y,12. 국민기초생활보장/(주거급여) 수급대상 가구 탈피 예상기간_y,12. 국민기초생활보장/(주거급여) 수급자 탈피 이유_y,"C.생활실태,\n만족 및 의식/(다)주거 환경 만족도_y"
0,0,2.0,NaN,2,3,3,92,1,NaN,100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,0,2.0,NaN,2,3,2,33,3,1.0,500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
2,0,2.0,NaN,1,3,3,73,1,NaN,40000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
3,0,2.0,NaN,2,3,3,92,1,NaN,70000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,0,2.0,NaN,2,3,3,92,1,NaN,70000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68521,0,2.0,NaN,5,3,3,99,2,1.0,30000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68522,0,2.0,NaN,5,3,3,76,2,1.0,10000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
68523,0,2.0,NaN,5,3,3,76,2,1.0,10000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
68524,0,2.0,NaN,5,3,3,76,2,1.0,10000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
68525,0,2.0,NaN,5,3,3,76,2,1.0,10000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0